# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/es7/bin/cmake

# The command to remove a file.
RM = /usr/local/es7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users7/cse/justinv/assignment-2-don-t-be-sentimental-justinv04

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users7/cse/justinv/assignment-2-don-t-be-sentimental-justinv04

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/es7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/es7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users7/cse/justinv/assignment-2-don-t-be-sentimental-justinv04/CMakeFiles /users7/cse/justinv/assignment-2-don-t-be-sentimental-justinv04//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users7/cse/justinv/assignment-2-don-t-be-sentimental-justinv04/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sentiment

# Build rule for target.
sentiment: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sentiment
.PHONY : sentiment

# fast build rule for target.
sentiment/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sentiment.dir/build.make CMakeFiles/sentiment.dir/build
.PHONY : sentiment/fast

#=============================================================================
# Target rules for targets named test_DSString

# Build rule for target.
test_DSString: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_DSString
.PHONY : test_DSString

# fast build rule for target.
test_DSString/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_DSString.dir/build.make CMakeFiles/test_DSString.dir/build
.PHONY : test_DSString/fast

DSString.o: DSString.cpp.o
.PHONY : DSString.o

# target to build an object file
DSString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sentiment.dir/build.make CMakeFiles/sentiment.dir/DSString.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_DSString.dir/build.make CMakeFiles/test_DSString.dir/DSString.cpp.o
.PHONY : DSString.cpp.o

DSString.i: DSString.cpp.i
.PHONY : DSString.i

# target to preprocess a source file
DSString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sentiment.dir/build.make CMakeFiles/sentiment.dir/DSString.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_DSString.dir/build.make CMakeFiles/test_DSString.dir/DSString.cpp.i
.PHONY : DSString.cpp.i

DSString.s: DSString.cpp.s
.PHONY : DSString.s

# target to generate assembly for a file
DSString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sentiment.dir/build.make CMakeFiles/sentiment.dir/DSString.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_DSString.dir/build.make CMakeFiles/test_DSString.dir/DSString.cpp.s
.PHONY : DSString.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sentiment.dir/build.make CMakeFiles/sentiment.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sentiment.dir/build.make CMakeFiles/sentiment.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sentiment.dir/build.make CMakeFiles/sentiment.dir/main.cpp.s
.PHONY : main.cpp.s

test_DSString.o: test_DSString.cpp.o
.PHONY : test_DSString.o

# target to build an object file
test_DSString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_DSString.dir/build.make CMakeFiles/test_DSString.dir/test_DSString.cpp.o
.PHONY : test_DSString.cpp.o

test_DSString.i: test_DSString.cpp.i
.PHONY : test_DSString.i

# target to preprocess a source file
test_DSString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_DSString.dir/build.make CMakeFiles/test_DSString.dir/test_DSString.cpp.i
.PHONY : test_DSString.cpp.i

test_DSString.s: test_DSString.cpp.s
.PHONY : test_DSString.s

# target to generate assembly for a file
test_DSString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_DSString.dir/build.make CMakeFiles/test_DSString.dir/test_DSString.cpp.s
.PHONY : test_DSString.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sentiment"
	@echo "... test_DSString"
	@echo "... DSString.o"
	@echo "... DSString.i"
	@echo "... DSString.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test_DSString.o"
	@echo "... test_DSString.i"
	@echo "... test_DSString.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

